### ISSUE TITLE
Script stops as soon as data is sent via mqtt

### ISSUE THREAD

**Issue by MaxMerdes** [Claudiuivan1/IoT-Project#1]
Hi, I have a problem with the dbprocess.py script. From the moment data comes in via mqtt the script stops with the following error message:

DB process starting...
Connected to DB
subscribing
subscribed
Traceback (most recent call last):
  File "dbprocess.py", line 80, in <module>
    main()
  File "dbprocess.py", line 57, in main
    msg = json.loads( msg.payload )
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 2 - line 1 column 4 (char 1 - 3)
root@max-Virtual-Machine:/home/max/sqlmqtt#

Can someone help me?

**Comment by Claudiuivan1** [comment]
Are you sure you built the database properly? Maybe the script isn't able to insert new data because of the wrong structure

**Comment by MaxMerdes** [comment]
> Are you sure you built the database properly? Maybe the script isn't able to insert new data because of the wrong structure

I have created the database with the following commands:

CREATE DATABASE sensors;

USE sensors;

CREATE TABLE sensors ( id INT, data VARCHAR(100), time_id INT AUTO_INCREMENT PRIMARY KEY ) 

CREATE USER 'python_logger'@'localhost' IDENTIFIED BY 'supersecure';

GRANT ALL PRIVILEGES ON sensors.* to 'python_logger'@'localhost';



I think the problem is in the line: msg = json.loads( msg.payload )
But I do not know what exactly the problem is.

**Comment by Claudiuivan1** [comment]
Yes! Have you encoded the messages sent through MQTT in a JSON structure? If the message is not well encoded, that line will fail to build the associated JSON structure.

**Comment by Claudiuivan1** [comment]
Is the problem solved? @MaxMerdes

**Comment by MaxMerdes** [comment]
Unfortunately no. After reinstalling Python, it stops at a later point in the script.
For testing, I have inserted the command print (msg) several times into the script.
Via mqtt i've sent a "4" as an INT.
You will find the error message on the screenshot:
![2021-01-16 14_27_25-](https://user-images.githubusercontent.com/70111815/104838839-b72a5480-58bd-11eb-9808-cc0e8d1df6ef.png)

**Comment by Claudiuivan1** [comment]
As I said before, the message has to be encoded as JSON. This script is encoded for a specific structure of the message. You can try to modify this part of the script in order to deal with your message structure:
`# Working on data to avoid error on mysql insert
		msg = json.loads( msg.payload )
		
		data = '{'
		
		for key in msg["data"]:
			data += '"' + key + '": "' + str( msg["data"][key] ) + '", '
		k = data.rfind(', ')
		data = data[:k] + data[k+1:]	
		
		data += '}'	

		# Insert into DB
		if( not saved[int(msg["id"])-1] ):
			sql_insert( conn, [msg["id"], data] )
			print( msg["id"] + " -> " + data )
			saved[int(msg["id"])-1] = True`

Or you can structure your messages in the same way I structured them:
`{"id": "<number>", "data": {"temp": "<value>", "hum": "<value>", "w_dir": "<value>", "w_int": "<value>", "r_heig": "<value>"}}`

I think you need to edit the code, as the msg structure is too specific. Let me know if you manage to solve the problem

**Comment by Claudiuivan1** [comment]
As I said before, the message has to be encoded as JSON. This script is encoded for a specific structure of the message. You can try to modify this part of the script in order to deal with your message structure:

`# Working on data to avoid error on mysql insert
		msg = json.loads( msg.payload )
		
		data = '{'
		
		for key in msg["data"]:
			data += '"' + key + '": "' + str( msg["data"][key] ) + '", '
		k = data.rfind(', ')
		data = data[:k] + data[k+1:]	
		
		data += '}'	

		# Insert into DB
		if( not saved[int(msg["id"])-1] ):
			sql_insert( conn, [msg["id"], data] )
			print( msg["id"] + " -> " + data )
			saved[int(msg["id"])-1] = True`

Or you can structure your messages in the same way I structured them:
`{"id": "<number>", "data": {"temp": "<value>", "hum": "<value>", "w_dir": "<value>", "w_int": "<value>", "r_heig": "<value>"}}`

I think you need to edit the code, as the msg structure is too specific. Let me know if you manage to solve the problem
